"""Tests verifying the fixes for the 6 bugs documented in research.md."""

import pytest

from uniaf3.schema import AF3Config, ChaiConfig, ProtenixConfig, UniAF3Config
from uniaf3.schema.base import (
    Atom,
    AuxiliaryParams,
    ContactRestraint,
    CovalentBond,
    Glycan,
    Ligand,
    PocketRestraint,
    Polymer,
    PolymerType,
    ProteinSeq,
    SequenceModification,
)

# ruff: noqa: S101


class TestBug1ToUniaf3MsaDir:
    """Bug 1: to_uniaf3 missing msa_dir argument for AlphaFold3 conversion."""

    def test_to_uniaf3_af3_does_not_crash(
        self, af3_conf: AF3Config, tmp_path_factory: pytest.TempPathFactory
    ):
        """to_uniaf3() with AF3Config should not raise TypeError."""
        from uniaf3.adapters import to_uniaf3

        msa_dir = tmp_path_factory.mktemp("msa_bug1")
        result = to_uniaf3(af3_conf, msa_dir=msa_dir)
        assert isinstance(result, UniAF3Config)

    def test_to_uniaf3_af3_preserves_sequences(
        self, af3_conf: AF3Config, tmp_path_factory: pytest.TempPathFactory
    ):
        """to_uniaf3() for AF3 should produce the same number of sequences."""
        from uniaf3.adapters import to_uniaf3

        msa_dir = tmp_path_factory.mktemp("msa_bug1b")
        result = to_uniaf3(af3_conf, msa_dir=msa_dir)
        assert len(result.sequences) == len(af3_conf.sequences)


class TestBug2ChaiCovalentBondAtom2:
    """Bug 2: to_chai covalent bond emits atom1 data for both atoms."""

    def test_covalent_bond_atom2_differs_from_atom1(
        self, uniaf3_conf: UniAF3Config
    ):
        """Chai covalent restraint should use atom2's data for the second side."""
        from uniaf3.adapters import to_chai

        chai = to_chai(uniaf3_conf, strict=False)
        assert chai.restraints is not None

        cov = [r for r in chai.restraints if r.connection_type == "covalent"]
        assert len(cov) == 1
        r = cov[0]

        # atom1 is on chain B (protein), atom2 is on chain D (ligand)
        # Protein side should have format: {residue_name}{residue_idx}@{atom_name}
        # Ligand side should have format: @{atom_name}
        assert "@" in r.res_idxA
        assert "@" in r.res_idxB

        # The key fix: res_idxA and res_idxB should NOT be the same
        # (they reference different atoms on different chains)
        assert r.res_idxA != r.res_idxB

        # Verify atom2 data is correctly used
        src = uniaf3_conf.covalent_bonds[0]
        # res_idxB should reference atom2's atom name
        assert src.atom2.atom_name in r.res_idxB


class TestBug3ProtenixPocketCopyIdx:
    """Bug 3: _from_protenix pocket constraint copy_idx off-by-one."""

    def test_pocket_contact_chain_matches_binder_copy1(
        self, protenix_confs: ProtenixConfig
    ):
        """Pocket contact residues with copy=1 should map to first chain (index 0)."""
        from uniaf3.adapters import from_protenix

        result = from_protenix(protenix_confs)
        uni = result[0]

        assert uni.pocket_restraints is not None
        assert len(uni.pocket_restraints) == 1
        pk = uni.pocket_restraints[0]

        # Entity 1 has count=2 → chains A, B
        # contact_residues has entity=1, copy=1 → should be chain "A" (index 0)
        assert pk.contact_tokens[0].chain_id == "A"

        # Entity 4 is the ligand (CCD_ATP), copy=1
        # binder_chain should also correctly use copy_idx-1
        assert pk.binder_chain is not None


class TestBug4ChainIdConsistency:
    """Bug 4: _next_chain_ids inconsistency with int_to_letters."""

    def test_chain_ids_consistent_with_int_to_letters(
        self, af3_server_confs
    ):
        """Chain IDs generated by AF3 Server adapter should match int_to_letters()."""
        from uniaf3.adapters import from_alphafold3_server
        from uniaf3.constant import int_to_letters

        result = from_alphafold3_server(af3_server_confs)
        uni = result[0]

        # Verify first few chain IDs follow int_to_letters convention
        expected_idx = 1
        for seq in uni.sequences:
            if isinstance(seq.id, list):
                for chain_id in seq.id:
                    assert chain_id == int_to_letters(expected_idx)
                    expected_idx += 1
            else:
                assert seq.id == int_to_letters(expected_idx)
                expected_idx += 1


class TestBug5BoltzMsaCsvPath:
    """Bug 5: from_boltz MSA directory path mismatch for CSV format."""

    def test_a3m_msa_writes_to_a3ms_subdir(
        self, boltz_conf, tmp_path_factory: pytest.TempPathFactory
    ):
        """A3M MSA files should be written to msa_dir/a3ms/ subdirectory."""
        from uniaf3.adapters import from_boltz

        msa_dir = tmp_path_factory.mktemp("msa_bug5")
        result = from_boltz(boltz_conf, msa_dir=msa_dir)

        # If the protein has an MSA, the unpaired_msa property should resolve
        prot = result.sequences[0]
        if isinstance(prot, ProteinSeq) and prot.msa_dir is not None:
            # The MSA files should be under the a3ms/ subdirectory
            msa_path = prot.unpaired_msa
            if msa_path is not None:
                assert "/a3ms/" in str(msa_path)


class TestBug6ChaiPocketNone:
    """Bug 6: from_chai pocket dict check always True."""

    def test_no_pocket_restraints_returns_none(self):
        """from_chai should return None for pocket_restraints when no pockets exist."""
        from uniaf3.adapters import from_chai

        # Create a Chai config with contact and covalent restraints but no pocket
        from uniaf3.schema.chai import ChaiEntity, ChaiRestraint

        conf = ChaiConfig(
            entities=[
                ChaiEntity(
                    entity_type="protein",
                    entity_name="A",
                    sequence="MVLSPADKTNVK",
                ),
                ChaiEntity(
                    entity_type="protein",
                    entity_name="B",
                    sequence="GKVGAHAG",
                ),
            ],
            restraints=[
                ChaiRestraint(
                    restraint_id="r0",
                    chainA="A",
                    res_idxA="V2",
                    chainB="B",
                    res_idxB="K2",
                    connection_type="contact",
                    max_distance_angstrom=8.0,
                ),
            ],
        )

        result = from_chai(conf)
        # With the fix, pocket_restraints should be None (not [])
        assert result.pocket_restraints is None
